format: hex #Цветовой формат - hex или minimessage
messages:
  no-perm: "&7[&6&lVE&7] &fУ вас нету прав!"
  reload: "&7[&6&lVE&7] &eУспешная перезагрузка"
  help:
    - "&7[&6&lVE&7] Список команд:"
    - "&6/%label% help &f- Вывод этого сообщения"
    - "&6/%label% join &f- Присоединиться к ивенту"
    - "&6/%label% delay &f- Время до начала/конца ивента"
    - "&6/%label% library &f- Меню с ценными предметами"
  success: "&7[&6&lVE&7] &aВы успешно присоединились к ивенту!"
  already-joined: "&7[&6&lVE&7] &cВы уже участвуете в ивенте!"
  not-active: "&7[&6&lVE&7] &cСейчас нет активного ивента!"
  max-players: "&7[&6&lVE&7] &cДостигнут лимит участников ивента!"
  console: "&7[&6&lVE&7] &cЭта команда только для игроков!"
  event-already-started: "&7[&6&lVE&7] &cИвент уже запущен!"
  delay: "&7[&6&lVE&7] &fДо &6%event_status%&f ивента осталось: &6%hours%ч %minutes%м %seconds%с"
